# Generated by Django 5.2.1 on 2025-06-15 15:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "ordering": ["last_name", "first_name"],
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                max_length=150,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_username",
                        message="Username должен содержать только латинские буквы, цифры, знаки @ + - .",
                        regex="^[\\w.@+-]+$",
                    )
                ],
                verbose_name="Уникальный юзернейм",
            ),
        ),
    ]
