# Generated by Django 5.2.1 on 2025-06-15 15:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0003_alter_follow_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="amountingredientinrecipe",
            options={
                "ordering": ("recipe", "ingredient"),
                "verbose_name": "Ингредиент в рецепте",
                "verbose_name_plural": "Ингредиенты в рецептах",
            },
        ),
        migrations.AlterModelOptions(
            name="follow",
            options={
                "ordering": ["-id"],
                "verbose_name": "Подписка",
                "verbose_name_plural": "Подписки",
            },
        ),
        migrations.AlterModelOptions(
            name="recipe",
            options={
                "ordering": ["-id"],
                "verbose_name": "Рецепт",
                "verbose_name_plural": "Рецепты",
            },
        ),
        migrations.AlterModelOptions(
            name="userfavorite",
            options={
                "ordering": ["-id"],
                "verbose_name": "Избранный рецепт",
                "verbose_name_plural": "Избранные рецепты",
            },
        ),
        migrations.AlterModelOptions(
            name="wishlist",
            options={
                "ordering": ["-id"],
                "verbose_name": "Список покупок",
                "verbose_name_plural": "Списки покупок",
            },
        ),
        migrations.AlterField(
            model_name="amountingredientinrecipe",
            name="amount",
            field=models.PositiveSmallIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(
                        1, "Количество ингредиента не должго быть меньше 1"
                    )
                ],
                verbose_name="Количество ингредиента",
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="cookingTime",
            field=models.PositiveSmallIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(
                        1, "Время приготовления не может быть меньше 1 минуты"
                    )
                ],
                verbose_name="Время приготовления (в минутах)",
            ),
        ),
    ]
